workflows:
  my-workflow:
    max_build_duration: 120
    scripts:
      - name: unzip
        script: unzip *.ipsw
      - name: build
        script: python3 ~/clone/ios_install.py
    artifacts:
      - tools/*.ipa
